name: Transfer files in repository to Remote Server via SCP
description: Transfer files from a specified path to a remote server via SCP.
author: Abhishek Ranjan

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  host:
    description: 'Remote host'
    required: true
  ssh_port: 
    description: 'Remote port'
    default: 22
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_key:
    description: 'SSH Key for authentification'
    required: true
  ssh_passphrase:
    description: 'ssh key passphrase'
  source_file:
    description: "Source file path to copy"
    required: true
  destination_dir:
    description: "Remote server destination directory"
    required: true
  rm:
    description: 'remove target folder before upload data'
    default: false


outputs: {}

branding:
  icon: 'copy'
  color: 'white'
